name: PR Coverage Comment
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

permissions:
  pull-requests: write
  contents: read

jobs:
  comment:
    name: Comment Jacoco Report to PR safely
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v6
        with:
          name: jacoco-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}/jacoco

      - name: Add JaCoCo coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ steps.download-artifact.outputs.download-path }}/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true